name: Merge verify files
description: "A composite action that call competitive-verifier merge-input"
author: "Kzrnm"
branding:
  color: blue
  icon: target
inputs:
  verify-files:
    description: "The file path of verify_files.json."
    required: true
  output-path:
    description: "The file path of merged json."
    required: true
    default: "./verify_files.json"
  working-directory:
    description: Specifies the working directory where the command is run.
    required: false
outputs:
  json-path:
    description: "The file path of merged json."
    value: ${{ steps.path.outputs.json-path }}
runs:
  using: composite
  steps:
    - name: merge
      id: merge
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        COMPETITIVE_FILES=( ${{ inputs.verify-files }} )
        competitive-verifier merge-input "${COMPETITIVE_FILES[@]}" | tee "$COMPETITIVE_OUTPUT_FILE"
      env:
        COMPETITIVE_OUTPUT_FILE: ${{ inputs.output-path }}

    - name: Path
      id: path
      shell: pwsh
      working-directory: ${{inputs.working-directory}}
      run: |
        $output = (Get-Item "${{ inputs.output-path }}").FullName
        echo "json-path=$output" >> $env:GITHUB_OUTPUT
