name: "competitive-verifier verify"
description: "A composite action that competitive-verifier verify"
author: "Kzrnm"
branding:
  color: blue
  icon: zap
inputs:
  verify-files:
    description: "The file path of verify files json. default: $COMPETITIVE_VERIFY_FILES_PATH environment variable."
    required: false
    default: ""
  write-summary:
    description: If true, show GitHub Actions Summary
    required: false
    default: "false"
  timeout:
    description: Timeout seconds
    required: false
    default: ""
  tle:
    description: TLE threshold seconds
    required: false
    default: ""
  prev-result:
    description: Previous result json file
    required: false
    default: ""
  destination:
    description: Output file path. If destination is empty, this action doesn't write result file.
    required: false
    default: ""
  split-size:
    description: "Size of split. Argument of verify --split."
    required: false
    default: ""
  split-index:
    description: "Argument of verify --split-index."
    required: false
    default: ""
  check:
    description: "If check is true and `verify` fails, the action fails too."
    required: false
    default: "false"
  verbose:
    description: If true, debug log is enabled.
    required: false
    default: "false"
  working-directory:
    description: Specifies the working directory where the command is run.
    required: false
outputs:
  is-success:
    description: "Result boolean of `competitive-verifier verify`."
    value: ${{ steps.verify.outputs.success }}

runs:
  using: composite
  steps:
    - name: Run verify
      shell: bash
      id: verify
      working-directory: ${{inputs.working-directory}}
      run: |
        if competitive-verifier \
          ${{ fromJson(inputs.verbose)       && '--verbose'       || '' }} \
          verify --check-error \
          ${{ fromJson(inputs.write-summary) && '--write-summary' || '' }} \
          ${{ format(inputs.timeout     && '--timeout {0}',     inputs.timeout) }} \
          ${{ format(inputs.tle         && '--tle {0}',         inputs.tle) }} \
          ${{ format(inputs.prev-result && '--prev-result {0}', inputs.prev-result) }} \
          ${{ format(inputs.split-size  && '--split {0}',       inputs.split-size) }} \
          ${{ format(inputs.split-index && '--split-index {0}', inputs.split-index) }} \
          ${{ format(inputs.destination && '--output "{0}"',    inputs.destination) }} ; then
          echo "success=true" >> $GITHUB_OUTPUT
        else
          echo "success=false" >> $GITHUB_OUTPUT
          ${{ fromJson(inputs.check) && 'exit 1' || '' }}
        fi
      env:
        COMPETITIVE_VERIFY_FILES_PATH: ${{ inputs.verify-files || env.COMPETITIVE_VERIFY_FILES_PATH }}
