name: "oj-resolve"
description: "A composite action that competitive-verifier oj-resolve"
author: "Kzrnm"
branding:
  color: blue
  icon: target
inputs:
  output-path:
    description: "The file path of oj-resolve result json."
    required: true
    default: ${{runner.temp}}/verify-files.json
  include:
    description: "Argument of oj-resolve --include."
    required: false
    default: ""
  exclude:
    description: "Argument of oj-resolve --exclude."
    required: false
    default: ""
  config:
    description: "Argument of oj-resolve --config."
    required: false
    default: ""
outputs:
  json-path:
    description: "The path of verify files json."
    value: ${{ steps.resolve.outputs.json-path }}
runs:
  using: composite
  steps:
    - name: oj-resolve
      shell: bash
      id: resolve
      run: |
        competitive-verifier oj-resolve --include $include --exclude $exclude $config | tee "$OUTPUT_FILE"
        echo "json-path=$OUTPUT_FILE" >> $GITHUB_OUTPUT
      env:
        include: ${{ inputs.include }}
        exclude: ${{ inputs.exclude }}
        config: ${{ (inputs.config != '') && '--config' || '' }} ${{inputs.config}}
        OUTPUT_FILE: ${{ inputs.output-path }}
