name: "oj-resolve"
description: "A composite action that competitive-verifier oj-resolve"
author: "Kzrnm"
branding:
  color: blue
  icon: target
inputs:
  output-path:
    description: "The file path of oj-resolve result json."
    required: true
    default: ${{runner.temp}}/verify-files.json
  include:
    description: "Argument of oj-resolve --include."
    required: false
    default: ""
  exclude:
    description: "Argument of oj-resolve --exclude."
    required: false
    default: ""
  config:
    description: "Argument of oj-resolve --config."
    required: false
    default: ""
  working-directory:
    description: Specifies the working directory where the command is run.
    required: false
outputs:
  json-path:
    description: "The path of verify files json."
    value: ${{ steps.path.outputs.json-path }}
runs:
  using: composite
  steps:
    - name: oj-resolve
      shell: bash
      id: resolve
      working-directory: ${{inputs.working-directory}}
      run: |
        set -f
        COMPETITIVE_include=(${{ inputs.include }})
        if test "${#COMPETITIVE_include[@]}" -ne 0; then
          COMPETITIVE_include=("--include" "${COMPETITIVE_include[@]}")
        fi

        COMPETITIVE_exclude=(${{ inputs.exclude }})
        if test "${#COMPETITIVE_exclude[@]}" -ne 0; then
          COMPETITIVE_exclude=("--exclude" "${COMPETITIVE_exclude[@]}")
        fi

        competitive-verifier oj-resolve \
          "${COMPETITIVE_include[@]}" \
          "${COMPETITIVE_exclude[@]}" \
          ${{ format(inputs.config && '--config "{0}"', inputs.config) }} | tee "$COMPETITIVE_OUTPUT_FILE"
        echo "json-path=$COMPETITIVE_OUTPUT_FILE" >> $GITHUB_OUTPUT
      env:
        COMPETITIVE_OUTPUT_FILE: ${{ inputs.output-path }}

    - name: Path
      id: path
      shell: pwsh
      working-directory: ${{inputs.working-directory}}
      run: |
        $output = (Get-Item "${{ inputs.output-path }}").FullName
        echo "json-path=$output" >> $env:GITHUB_OUTPUT
