name: "oj-resolve"
description: "A composite action that competitive-verifier oj-resolve"
author: "Kzrnm"
branding:
  color: blue
  icon: target
inputs:
  output-path:
    description: "The file path of oj-resolve result json."
    required: true
    default: ${{runner.temp}}/verify-files.json
  include:
    description: "Argument of oj-resolve --include."
    required: false
    default: ""
  exclude:
    description: "Argument of oj-resolve --exclude."
    required: false
    default: ""
  config:
    description: "Argument of oj-resolve --config."
    required: false
    default: ""
outputs:
  json-path:
    description: "The path of verify files json."
    value: ${{ steps.resolve.outputs.json-path }}
runs:
  using: composite
  steps:
    - name: oj-resolve
      shell: bash
      id: resolve
      run: |
        set -f
        competitive-verifier oj-resolve --include $COMPETITIVE_include --exclude $COMPETITIVE_exclude $(set +f && echo $COMPETITIVE_config) | tee "$COMPETITIVE_OUTPUT_FILE"
        echo "json-path=$COMPETITIVE_OUTPUT_FILE" >> $GITHUB_OUTPUT
      env:
        COMPETITIVE_include: ${{ inputs.include }}
        COMPETITIVE_exclude: ${{ inputs.exclude }}
        COMPETITIVE_config: ${{ format(inputs.config && '--config {0}', inputs.config) }}
        COMPETITIVE_OUTPUT_FILE: ${{ inputs.output-path }}
