name: Test merge-result

on:
  push:
    branches:
      - main
    paths:
      - merge-result/**
      - .github/workflows/test-merge-result.yml
  pull_request:
    paths:
      - merge-result/**
      - .github/workflows/test-merge-result.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up competitive-verifier
        uses: ./setup
        with:
          cache-pip: true

      - name: Use glob
        id: glob
        uses: ./merge-result
        with:
          result-files: merge-result/tests/pyres*/*.json
          output-path: merged-glob.json

      - name: Use list
        id: list
        uses: ./merge-result
        with:
          result-files: |
            merge-result/tests/pyres0/competitive-verifier-result.json
            merge-result/tests/pyres1/competitive-verifier-result.json
            merge-result/tests/pyres2/competitive-verifier-result.json
            merge-result/tests/pyres3/competitive-verifier-result.json
          output-path: merged-list.json

      - name: In subdir
        id: subdir
        uses: ./merge-result
        with:
          result-files: pyres*/competitive-verifier-result.json
          working-directory: merge-result/tests
          output-path: merged-subdir.json

      - name: Check path
        run: |
          test "${{steps.glob.outputs.json-path}}" = "$GITHUB_WORKSPACE/merged-glob.json"
          test "${{steps.list.outputs.json-path}}" = "$GITHUB_WORKSPACE/merged-list.json"
          test "${{steps.subdir.outputs.json-path}}" = "$GITHUB_WORKSPACE/merge-result/tests/merged-subdir.json"

      - name: Check glob
        uses: ./testing/verifier-object-equality-action
        with:
          class: VerifyCommandResult
          file1: ${{steps.glob.outputs.json-path}}
          file2: merge-result/tests/merged.json

      - name: Check list
        uses: ./testing/verifier-object-equality-action
        with:
          class: VerifyCommandResult
          file1: ${{steps.list.outputs.json-path}}
          file2: merge-result/tests/merged.json

      - name: Check subdir
        uses: ./testing/verifier-object-equality-action
        with:
          class: VerifyCommandResult
          file1: ${{steps.subdir.outputs.json-path}}
          file2: merge-result/tests/merged.json
