name: Test setup

on:
  push:
    branches:
      - main
    paths:
      - setup/**
      - .github/workflows/test-setup.yml
  pull_request:
    paths:
      - setup/**
      - .github/workflows/test-setup.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python 3.x
        uses: ./setup
        with:
          cache-pip: true

      - name: Python 3.9
        uses: ./setup
        id: python39
        with:
          cache-pip: true
          python-version: "3.9"
          package: competitive-verifier==1.2.1-dev
      - name: Test 3.9
        run: |
          [ "${{ steps.python39.outputs.version }}" = "1.2.1.dev0" ]


      - name: Python 3.10
        uses: ./setup
        id: python310
        with:
          python-version: "3.10"
          package: git+https://github.com/competitive-verifier/competitive-verifier.git@eeb93b5c71fb1caac9a439c936c13a384387db84
      - name: Test 3.10
        run: |
          [ "${{ steps.python310.outputs.version }}" = "0.0.1" ]
