name: Test oj-resolve

on:
  push:
    branches:
      - main
    paths:
      - oj-resolve/**
      - .github/workflows/test-oj-resolve.yml
  pull_request:
    paths:
      - oj-resolve/**
      - .github/workflows/test-oj-resolve.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up competitive-verifier
        uses: ./setup
        with:
          cache-pip: true

      - name: oj-resolve with include
        id: include
        uses: ./oj-resolve
        with:
          include: oj-resolve/examples/python
          output-path: ./verify-files.json
      - name: oj-resolve with exclude
        id: exclude
        uses: ./oj-resolve
        with:
          include: oj-resolve/examples/
          exclude: |
            oj-resolve/examples/java
            scripts
          output-path: ${{runner.temp}}/verify-files.json
      - name: oj-resolve all
        id: all
        uses: ./oj-resolve
        with:
          output-path: verify-files-all.json
      - name: oj-resolve with awk
        id: awk
        uses: ./oj-resolve
        with:
          include: oj-resolve/examples/
          config: oj-resolve/examples/awk-config.toml
          output-path: verify-files-with-awk.json
      - name: Check path
        run: |
          test "${{steps.include.outputs.json-path}}" = "$GITHUB_WORKSPACE/verify-files.json"
          test "${{steps.exclude.outputs.json-path}}" = "$RUNNER_TEMP/verify-files.json"
          test "${{steps.all.outputs.json-path}}" = "$GITHUB_WORKSPACE/verify-files-all.json"
          test "${{steps.awk.outputs.json-path}}" = "$GITHUB_WORKSPACE/verify-files-with-awk.json"

      - name: Check awk
        run: |
          cat "${{steps.awk.outputs.json-path}}" | jq '.files."oj-resolve/examples/awk/circle.test.awk"' | grep "oj-resolve/examples/awk/circle.awk"

      - name: equal
        uses: ./testing/verifier-object-equality-action
        with:
          class: VerificationInput
          file1: ${{steps.include.outputs.json-path}}
          file2: ${{steps.exclude.outputs.json-path}}
      - name: Not equal
        uses: ./testing/verifier-object-equality-action
        with:
          class: VerificationInput
          file1: ${{steps.include.outputs.json-path}}
          file2: ${{steps.all.outputs.json-path}}
          not: true
      - name: Not equal awk
        uses: ./testing/verifier-object-equality-action
        with:
          class: VerificationInput
          file1: ${{steps.include.outputs.json-path}}
          file2: ${{steps.awk.outputs.json-path}}
          not: true

      - name: oj-resolve with awk in sub
        id: awk-sub
        uses: ./oj-resolve
        with:
          working-directory: oj-resolve/tests-sub
          config: awk-config.toml
          output-path: verify-files-with-awk.json
      - name: Check path in sub
        run: |
          test "${{steps.awk-sub.outputs.json-path}}" = "$GITHUB_WORKSPACE/oj-resolve/tests-sub/verify-files-with-awk.json"
      - name: Check awk-sub
        run: |
          cat "${{steps.awk-sub.outputs.json-path}}" | jq '.files."awk/circle.test.awk"' | grep "awk/circle.awk"
